### ISSUE TITLE
Melhorar a avaliação da linguagem                                               

### ISSUE THREAD

**Issue by fsantanna-uerj** [igormorse/EDL#1]
- readability/writability: melhorar argumentação                    
- expressividade: mostrar um exemplo mais representativo, que use características especiais da linguagem escolhida
- você instalou a linguagem e executou exemplos?

**Comment by igormorse** [comment]
No Slide que ainda não realizei o commit possui imagens do código no compilador online. ( O Slide ainda está incompleto, ainda estou desenvolvendo ele )

> você instalou a linguagem e executou exemplos?

Sim, tirando alguns trechos que tirei da página oficial do Groovy, todos os outros escrevi no compilador online de Groovy. ( HelloWorld.java/groovy , regEx.java/Groovy ) mas vou dar uma revisada para verificar se possui algum erro de sintaxe.

Eu notei que na planilha minha nota já foi inserida, haverá alguma distribuição de nota do artigo/nota de apresentação ?  A nota que está na planilha é a final ou haverá mudanças de acordo com as revisões que for fazendo nos pontos acima ?

No próximo commit irei melhorar os outros pontos.

**Comment by fsantanna** [comment]
A nota é temporária, pode melhorar o trabalho o quanto quiser...
